# Generated by Django 3.2 on 2022-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20220730_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(default=30, max_length=20),
            preserve_default=False,
        ),
    ]
