# Generated by Django 3.2 on 2022-07-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='phone',
        ),
    ]
