# Generated by Django 3.2 on 2022-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
    ]
