# Generated by Django 3.2 on 2022-07-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='is_mvp',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='photo',
        ),
    ]
