# Generated by Django 3.2 on 2022-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_is_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
